### ISSUE TITLE
Dropped items without strike action don't have an option to be picked up from the HUD

### ISSUE THREAD

**Issue by cass-f20** [Larkinabout/fvtt-token-action-hud-pf2e#60]
I have that when falling unconscious PCs automatically drop their items, weapons with strike action have no issue but items that only show in the inventory (like a shield) don't have an option to be picked up from the HUD for me, I think they should still show in the Inventory tab with the options of 1h, 2h, worn
Foundry v10, PF2e HUD 1.4.8

**Comment by Larkinabout** [comment]
Showing unequipped items is easy enough, but allowing items to be equipped or unequipped on the HUD itself might overcomplicate it. The HUD is structured so that each action is its own button, meaning, in its current form, the HUD would need individual Equip and Unequip buttons for every item. 

I'll ponder on it, but I believe there is a way to add an item as a strike and set it so that the item isn't removed when it's dropped. This would give you some control over which items to display and should allow you to use a strike's auxiliary options to requip the item from the HUD. Check out the reply in this issue: https://github.com/foundryvtt/pf2e/issues/8147
