### ISSUE TITLE
Strike names showing inconsistently

### ISSUE THREAD

**Issue by steev42** [Larkinabout/fvtt-token-action-hud-pf2e#76]
This may be something with my configuration or the custom creatures I'm using, but my monsters with multiple strikes are quite hard to use with the HUD if I want to switch between them. 
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/6807026/21e46862-826b-4ab0-a0f2-1f9579482080)

I can use the tooltip to figure out which weapon to use, and I'm getting used to which is which at this point, but I'd really like the game of the strike to be included.  I've tried selecting the "Show Strike Names" option in the settings (and in fact, that is active on that screenshot), but it doesn't seem to be consistent.  Some creatures have the weapon name (rapier seems to show up for one creature), others don't (the dogslicer and shortbow in the attached image).

Editing to add a working creature on the same scene:
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/6807026/dd2caf9f-0d76-4106-8cdf-862c2c303a80)

**Comment by Larkinabout** [comment]
Hi @steev42, the 'Show Strike Names' module setting is a by default setting. The reason is that if a user wants to hide strikes names by default except for a handful of strikes, we don't want the module setting to overwrite their individual choices.

If you want to show strikes names by default, you will need to either remove and re-add the Strikes group on the HUD or reset the layout via the Token Action HUD Core 'Reset Layout' module setting within the Layout menu. Be warned, the latter choice resets the whole HUD to the system default.

**Comment by steev42** [comment]
Ah, and it looks to be on a per-actor basis.  A little annoying for my purposes, but that does seem to fix the issue.  Thanks.
